### ISSUE TITLE
Support for async by default for HTTP/S3/GCS storage?

### ISSUE THREAD

**Issue by agoodm** [JuliaIO/Zarr.jl#105]
I have been benchmarking zarr access times in both Python and Julia and noticed that Zarr.jl was an order of magnitude slower. I read through the discussion in #65 and tried some of the tips mentioned but was still unable to fully bridge the gap between both versions. A key reason is because I am using zarr-python by itself to load the store in my benchmarks rather than using xarray/dask, the latter adds a ton of overhead in of itself with recent versions of dask. Here are my current benchmark results to help illustrate. 

Zarr.jl
```Julia
using Zarr

Zarr.Blosc.set_num_threads(8) # To match blosc defaults for python
g = zopen("https://mur-sst.s3.us-west-2.amazonaws.com/zarr-v1", consolidated=true)
s = g["analysed_sst"]
@time s[1:3600, 1:1799, 1:500]
# 27.208033 seconds (1.07 M allocations: 12.341 GiB, 4.61% gc time, 0.92% compilation time)
# Note I did this multiple times to eliminate compilation overhead. The machine I am testing on has around 3 Gbps of bandwidth.
```

```python
import zarr

g = zarr.open_consolidated("https://mur-sst.s3.us-west-2.amazonaws.com/zarr-v1")
s = g.analysed_sst
%time s[:500, :1799, :3600] # 100 chunks
# CPU times: user 3.25 s, sys: 5.1 s, total: 8.34 s
# Wall time: 3.6 s
```

When attempting to manually do async on each chunk I get:
```Julia
function async_read(xin)
    xout = similar(xin)
    @sync for i in Zarr.DiskArrays.eachchunk(xin)
       @async xout[i...] = xin[i...]
    end
    xout
end

v = view(s, 1:3600, 1:1799, 1:500)
@time async_read(v)
20.875799 seconds (94.77 k allocations: 24.339 GiB, 4.41% gc time)
3600×1799×500 Array{Int16, 3}:
```
This is barely any improvement and now memory usage has doubled. What I am suspecting is that the actual reason for the differences is that zarr-python has async built-in through fsspec, while Zarr.jl does not have this implemented in the storage backends. I think to bridge the gap it may be necessary to directly read the chunks asynchronously at the library level for the HTTP/GCS/S3 storage backends, doing it the way I have is probably creating a lot of overhead by allocating many small arrays for the chunks through calling `getindex` each time instead of allocating only one big array in one go. 

pinging @meggart and @alex-s-gardner in case you can suggest better methods mentioned than what I have tried so far.

**Comment by meggart** [comment]
Thanks a lot for raising this issue again and for bringing another nice and reproducible example. I also did some tests based on this. I did some experiments and I think the main issue with the async approach was that it was spawning too many tasks which somehow got into each other's way. Please check out this PR #106 and test if it works for you as well and how close we get to the python read times.
