### ISSUE TITLE
The `zarr-demo` s3 bucket appears to have been taken down?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaIO/Zarr.jl#164]
https://zarr-demo.s3-eu-west-2.amazonaws.com/ returns a "no such bucket" page.

That looks to be why tests are consistently failing...

**Comment by felixcremer** [comment]
Should we use a small dataset that we host at the institute for the tests? So that we are independent of aws?

**Comment by joshmoore** [comment]
cc: @alimanfoo regarding `zarr-demo` (see https://github.com/zarr-developers/zarr-python/issues/385#issuecomment-452447219)

Happy to help with a central resource if need be.

**Comment by alimanfoo** [comment]
Hi folks, I think I originally created the zarr-demo bucket but in one of our organisational AWS accounts that I no longer have direct access to. I'll chase up internally and see if I can find out what happened. 

In the interim, very happy to put something on GCS if useful.

**Comment by meggart** [comment]
Hi all, I removed the respective test in #170 . We are using a different dataset for testing S3 now.
