### ISSUE TITLE
Finding an org for Zarr.jl

### ISSUE THREAD

**Issue by meggart** [JuliaIO/Zarr.jl#25]
In the discussion at JuliaClimate https://github.com/JuliaClimate/meta/issues/1  it was suggested to move Zarr.jl to the JuliaClimate org and there were a few thumbs-ups for this. Do we see this as a consensus to move the package there? Or is additional discussion necessary. @visr @Balinus

**Comment by visr** [comment]
I think something can be said for each of JuliaIO, JuliaGeo and JuliaClimate. I'm happy with any of those.

**Comment by Balinus** [comment]
I agree with @visr here. The three org can be a natural choice fo this package. Having Zarr in JuliaClimate would be a major addition to the org, but it's up to you! I do not have experience with the format so I don't know if Zarr is mostly climate related or is it used widely elsewhere?

Integrating Zarr format is definitely on my radar.

**Comment by manics** [comment]
FYI Zarr is being actively worked on in the bio-imaging community: https://forum.image.sc/t/next-generation-file-formats-for-bioimaging/31361/

**Comment by joshmoore** [comment]
:+1: for Zarr.jl wherever it may live, and a heads up that some Outreachy applicants may be headed this way re: https://github.com/zarr-developers/zarr_implementations/issues/42

**Comment by mkitti** [comment]
I think JuliaIO would nake the most sense for this.

**Comment by mkitti** [comment]
https://github.com/JuliaIO

**Comment by meggart** [comment]
Thanks for the suggestion @mkitti Yes, probably it is good to host the package in a place where not only geo-related people are assembled to also give a voice to people from Bio-Imaging and similar fields. So I would be open for moving the package there.

**Comment by mkitti** [comment]
@meggart you should have just received an invite to JuliaIO in your email from @bjarthur. Let me know if you got it.

**Comment by meggart** [comment]
Yes, I received the invite. Have you moved a Julia package before? I am not really sure about the steps needed to not mess up the registry. Do you have any suggestions, or is it as simple as hitting the "move repository" button in the package settings and Github redirects will do the rest...

**Comment by visr** [comment]
https://github.com/JuliaRegistries/General/#how-do-i-transfer-a-package-to-an-organization-or-another-user

**Comment by mkitti** [comment]
Welcome to JuliaIO, Zarr.jl! Can this issue be closed now that the transition is complete:
https://github.com/JuliaRegistries/General/pull/52676
