### ISSUE TITLE
Joining the Zarr Implementation council

### ISSUE THREAD

**Issue by meggart** [JuliaIO/Zarr.jl#88]
This package (Zarr.jl) was invited to join the Zarr implementation council which will be installed in the future. In case we accept we have to nominate a representative who can join the meetings and speaks for the implementation. 

I would volunteer to represent Zarr.jl at the Implementation council, but of course wanted to check with other contributors on their opinions @visr @Alexander-Barth @Fbehr-data @mkitti 

 Reference to the zarr-governance issue: https://github.com/zarr-developers/governance/issues/18

**Comment by mkitti** [comment]
I think you would be the best person to represent this package. My main interest is in the OME NGFF effort built on top of Zarr.jl:
https://ngff.openmicroscopy.org/latest/

I would be happy to be involved as needed. I did volunteer to help out with the conformance testing, and I'm hoping to find some time to work on that.

**Comment by visr** [comment]
I saw the announcement, it looks like a good idea to have such a council. Glad that you're willing to represent Zarr.jl there @meggart! Will you also move the repository over to [zarr-developers](https://github.com/zarr-developers)?

**Comment by Alexander-Barth** [comment]
This is great for the visibility of Zarr.jl ! Thank you for volunteering to represent the julia perspective for Zarr !

**Comment by mkitti** [comment]
@bjarthur you may have an interest in this as well.

**Comment by meggart** [comment]
Thanks a lot for the support, I will communicate this in the respective zarr-governance issue.
